-- SKO Q&A Application Schema (ANUP schema)
-- Run each statement individually via MCP

-- Users
CREATE TABLE ANUP.SKO_USERS (
    USER_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL      VARCHAR2(255) UNIQUE NOT NULL,
    PASSWORD   VARCHAR2(255) NOT NULL,
    QUESTIONS_ASKED NUMBER DEFAULT 0,
    IS_ADMIN   NUMBER(1,0) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
--ENDSTMT

-- Question groups
CREATE TABLE ANUP.SKO_QUESTION_GROUPS (
    GROUP_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GROUP_TITLE VARCHAR2(500) NOT NULL,
    GROUP_SUMMARY VARCHAR2(2000),
    TOTAL_LIKES NUMBER DEFAULT 0,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
--ENDSTMT

-- Questions
CREATE TABLE ANUP.SKO_QUESTIONS (
    QUESTION_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID       NUMBER REFERENCES ANUP.SKO_USERS(USER_ID),
    QUESTION_TEXT VARCHAR2(2000) NOT NULL,
    LIKE_COUNT    NUMBER DEFAULT 0,
    GROUP_ID      NUMBER REFERENCES ANUP.SKO_QUESTION_GROUPS(GROUP_ID),
    IS_ACTIVE     NUMBER(1,0) DEFAULT 1,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
--ENDSTMT

-- Likes (one per user per question)
CREATE TABLE ANUP.SKO_LIKES (
    LIKE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID     NUMBER REFERENCES ANUP.SKO_USERS(USER_ID),
    QUESTION_ID NUMBER REFERENCES ANUP.SKO_QUESTIONS(QUESTION_ID),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_USER_QUESTION_LIKE UNIQUE (USER_ID, QUESTION_ID)
)
--ENDSTMT

-- Initial seed users (password = AskJay)
INSERT INTO ANUP.SKO_USERS (EMAIL, PASSWORD, IS_ADMIN) VALUES ('admin@oracle.com','AskJay',1)
--ENDSTMT
INSERT INTO ANUP.SKO_USERS (EMAIL, PASSWORD) VALUES ('test.user@oracle.com','AskJay')
--ENDSTMT
INSERT INTO ANUP.SKO_USERS (EMAIL, PASSWORD) VALUES ('jane.doe@oracle.com','AskJay')
--ENDSTMT
COMMIT
